# Stage 1. - Build process

FROM node:8 as build-deps

WORKDIR /opt/app

COPY package.json yarn.lock ./
RUN yarn

COPY . ./
RUN yarn build
RUN CI=true yarn test

# Stage 2. - Production environment

FROM httpd:2.4.38-alpine
COPY --from=build-deps /opt/app/build /usr/local/apache2/htdocs/

EXPOSE 80 

