---
type: object
properties:
  id:
    type: number
    readOnly: true
    example: 999
  name:
    type: string
    example: "Mail"
  abbreviation:
    type: string
    example: "mail"
  description:
    type: string
    example: "Mail service"
  entity_id:
    type: string
    format: url
    example: "https://mail.com"
  contact_email:
    type: string
    example: "jdoe@service.com"
  security_email:
    type: string
    example: "jdoe@service.com"
  support_email:
    type: string
    example: "jdoe@service.com"
  uuid4:
    type: string
    format: uuid
    readOnly: true
    description: "Unique generated uuid for the cached image"
    example: "12035254-E1F1-4190-9E60-EDAEE8DEE72A"
  access_allowed_for_all:
    type: boolean
    description: "If true all collaborations can use this service"
    example: true
  automatic_connection_allowed:
    type: boolean
    description: "If true all collaborations can connect to this service"
    example: true
  code_of_conduct_compliant:
    type: boolean
    description: "Compliant with the code of conduct"
    example: true
  non_member_users_access_allowed:
    type: boolean
    description: "If true then non collaboration members can access this service"
    example: true
  public_visible:
    type: boolean
    description: "If true then this service is public visible"
    example: true
  research_scholarship_compliant:
    type: boolean
    description: "Compliant with the research scholarship"
    example: true
  sirtfi_compliant:
    type: boolean
    description: "Compliant with the sirtfi"
    example: true
  token_enabled:
    type: boolean
    description: "Can tokens be created for users"
    example: true
  white_listed:
    type: boolean
    description: "Is this service whitelisted"
    example: true
  token_validity_days:
    type: number
    description: "Tokens validity days"
    example: 30
  accepted_user_policy:
    type: string
    format: uri
    example: "https://service.universiteitvanharderwijk.nl/aup"
  privacy_policy:
    type: string
    format: uri
    example: "https://service.universiteitvanharderwijk.nl/privacy"
  logo:
    type: string
    format: uri
    descriotion: "URL for the logo"
    example: "http://localhost:8080/api/images/collaborations/b7f621e3-de98-4de4-aca0-1573f4eb8339"
  created_at:
    type: number
    description: "The date of the created at in epoch seconds"
    example: 1644015600
  created_by:
    type: string
    description: "UID of the user who created this"
    example: "urn:admin"
  updated_by:
    type: string
    description: "UID of the user who updated this"
    example: "urn:admin"
