---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for client
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25

  # Maintain dependencies for server
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
