---
language: python
env:
  CODECOV_TOKEN: "ae851f67-c91a-4063-8bd6-a9fc74b3173e"

services:
  - docker

python:
  - "3.6"

cache:
  pip: true
  yarn: true
  directories:
    - "node_modules"
    - "$HOME/docker"

notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      - surfnet-nl:tEtfF52tuZaz02sdjLJ2XGUY

jobs:
  include:
    #######################################################
    ## Build, run local tests, and check code coverage ####
    #######################################################
    - stage: test
      before_install:
        - pip install -r ./server/requirements/test.txt
        - pip install codecov
        - "rm -fr ~/.yarn"
        - "curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3"
        - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
        - yarn -v
        - nvm install v8.12.0
        - nvm use v8.12.0
      before_script:
        - >
          mysql -uroot -e "
            create database IF NOT EXISTS sbs_test;
            CREATE USER 'sbs'@'localhost' IDENTIFIED BY 'sbs';
            GRANT ALL PRIVILEGES ON *.* TO 'sbs'@'localhost' WITH GRANT OPTION;
          "
      script:
        - pytest --cov=server --cov-report= server/test
        - flake8 ./server/
        - yarn -v
        - node -v
        - cd client
        - yarn install
        - CI=true yarn test
        - yarn build
      after_success:
        - codecov

    #######################################################
    ## Build and upload docker images #####################
    #######################################################
    - stage: build containers
      before_install:
        - ./script/travis-cache-docker.sh load
      script:
        - ./scripts/build-server.sh
        - ./scripts/build-client.sh
      before_cache:
        - ./script/travis-cache-docker.sh save

      after_success:
        - >
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push surfscz/sbs-server
        - docker push surfscz/sbs-client
