# Build SRAM SBS (apache) server image
FROM ghcr.io/openconext/openconext-basecontainers/apache2:latest AS sram-sbs-client

RUN rm -f /etc/apache2/sites-enabled/*.conf
COPY client/apache.conf /etc/apache2/sites-enabled/apache.conf

RUN a2enmod proxy_wstunnel

# Set the default workdir
WORKDIR /opt

# Install SBS
COPY sbs.tar.xz /opt/sbs.tar.xz

# Untar sbs
RUN tar -Jxf sbs.tar.xz

#CMD ["bash"]

