# Build SRAM SBS (apache) server image
FROM ghcr.io/openconext/openconext-basecontainers/apache2:latest AS sram-sbs-client

# Copy init script
COPY --chmod=0755 misc/container-init-pre.sh  /container-init/sbs_prepare.sh

RUN rm -f /etc/apache2/sites-enabled/*.conf
COPY etc/apache.conf /etc/apache2/sites-enabled/apache.conf

RUN a2enmod proxy_wstunnel

# Set the default workdir
WORKDIR /opt

# Install SBS
COPY sbs.tar.xz /opt/sbs.tar.xz

# Untar sbs
RUN tar -Jxf sbs.tar.xz
