---
volumes:
  data:
    driver: "local"
  cloudbeaver:
    driver: "local"

services:
  redis:
    image: "docker.io/redis"
    container_name: "sbs-redis"

  client:
    build: "client"
    container_name: "sbs-client"
    restart: "no"
    links:
      - "server"
    ports:
      - "3000:3000"
    volumes:
      - "${PWD}/client:/opt/app/client"

  server:
    build: "server"
    container_name: "sbs-server"
    restart: "no"
    links:
      - "db"
      - "redis"
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}/etc/config.yml:/etc/config.yml"
      - "${PWD}/server:/opt/server"
    environment:
      CONFIG_TEMPLATE: "/etc/config.yml"
      TESTING: 1
      PROFILE: "local"
      ALLOW_MOCK_USER_API: 1
      DATABASE_URI: "mysql+mysqldb://sbs:sbs@db/sbs?charset=utf8mb4"
      REDIS_URI: "redis://redis:6379/"
      BASE_URL: "http://localhost:8080"
      SOCKET_URL: "0.0.0.0:8080/"
      SECRET: "${SECRET:-geheim}"
      CLIENT_ID: "${CLIENT_ID:-foo}"
      CLIENT_SECRET: "${CLIENT_SECRET:-echtgeheim}"
      AUDIENCE: "${AUDIENCE:-http://localhost:9001}"
      ADMIN: "${ADMIN:-urn:john}"
      LDAP_URL: "${LDAP_URL:-ldap://localhost:1389/dc=example,dc=org}"
      LDAP_BIND: "${LDAP_BIND:-cn=admin,dc=example,dc=org}"

  db:
    image: "docker.io/mariadb:11"
    container_name: "sbs-db"
    restart: "no"
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-sbs}"
      MARIADB_DATABASE: "sbs"
      MARIADB_USER: "sbs"
      MARIADB_PASSWORD: "sbs"
    ports:
      - "13306:3306"
    volumes:
      - "data:/var/lib/mysql:Z"
      - "${PWD}/etc/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"

  beaver:
    image: "dbeaver/cloudbeaver:latest"
    restart: "always"
    links:
      - db
    ports:
      - "8978:8978"
    volumes:
      - "cloudbeaver:/opt/cloudbeaver/workspace"
