# -*- coding: utf-8 -*-
#

volumes:
  data:
    driver: local

services:
  redis:
    image: redis
    container_name: redis

  client:
    build: client
    restart: "always"
    links:
      - server
    ports:
      - 8080:80
    volumes:
      - ${PWD}/etc/apache.conf:/etc/apache2/sites-enabled/sbs.conf:ro

  server:
    build: server
    restart: "always"
    links:
      - db
      - redis
    volumes:
      - ${PWD}/etc/config.yml:/etc/config.yml
      - ${PWD}/server:/opt/server
    ports:
      - 8080
    environment:
      CONFIG_TEMPLATE: /etc/config.yml
      TESTING: 1
      DATABASE_URI: mysql+mysqldb://sbs:sbs@db/sbs?charset=utf8mb4
      REDIS_URI: redis://redis:6379/
      BASE_URL: http://localhost:8080
      SOCKET_URL: 0.0.0.0:8080/
      SECRET: ${SECRET}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      AUDIENCE: ${AUDIENCE}
      ADMIN: ${ADMIN}
      LDAP_URL: ${LDAP_URL}
      LDAP_BIND: ${LDAP_BIND}

  db:
    image: mariadb:11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-sbs}
      MARIADB_DATABASE: sbs
      MARIADB_USER: sbs
      MARIADB_PASSWORD: sbs
    ports:
      - 13306:3306
    volumes:
      - data:/var/lib/mysql:Z
      - ${PWD}/etc/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
