# Build SRAM SBS (apache) server image
FROM ghcr.io/openconext/openconext-basecontainers/apache2:latest AS sram-sbs-server

RUN rm -f /etc/apache2/sites-enabled/*.conf
COPY etc/apache-dev.conf /etc/apache2/sites-enabled/apache.conf

# Set the default workdir
WORKDIR /opt
