version: "2"

services:

  db:
    image: mysql:8.0
    volumes:
      - ./etc/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./etc/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SECRET}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    networks:
      - backend
    restart: unless-stopped

  db_front:
    image: adminer
    links:
      - db
    ports:
      - 8080:8080
    networks:
      - backend
      - frontend
    restart: unless-stopped

  server:
    image: surfscz/sbs-server:test
    volumes:
      - ./log:/opt/app/log
      - ./etc/config.env:/tmp/config.env
      - ./etc/alembic.env:/tmp/alembic.env
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
    depends_on:
      - db
    networks:
      - frontend
      - backend
    ports:
      - ${BASE_PORT}:80
    environment:
      SECRET: ${SECRET}

      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}

      API_USER: ${API_USER}
      API_PASS: ${API_PASS}

      BASE_URL: ${BASE_URL}

      ADMIN_USERS: ${ADMIN_USERS}

      PROFILE: local
    command:
      - /bin/bash
      - -c
      - |
        envsubst < /tmp/config.env > server/config/config.yml
        envsubst < /tmp/config.env > server/config/test_config.yml
        envsubst < /tmp/alembic.env > server/migrations/alembic.ini
        echo "Waiting for Database..."
        nginx && python -m server
    restart: unless-stopped

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
