database:
  uri: "mysql+pymysql://sbs:sbs@localhost/sbs"

secret_key: secret

api_users:
  - name: "sysadmin"
    password: "secret"
    scope: "read, write"

mail:
  host: localhost
  port: 1025

base_url: http://localhost:3000