---
type: object
properties:
  id:
    type: number
    readOnly: true
    example: 888
  name:
    type: string
    example: "Cloud research service"
  abbreviation:
    type: string
    example: "cloud"
  description:
    type: string
    example: "A cloud research service, configured to mainly research cumulus formations."
  entity_id:
    type: string
    format: url
    example: "https://service.cloud.example.com"
  contact_email:
    type: string
    example: "jdoe@cloud.example.com"
  security_email:
    type: string
    example: "jdoe@cloud.example.com"
  support_email:
    type: string
    example: "jdoe@cloud.example.com"
  uuid4:
    type: string
    format: uuid
    readOnly: true
    description: "Unique generated uuid for the cached image"
    example: "12035254-E1F1-4190-9E60-EDAEE8DEE72A"
  access_allowed_for_all:
    type: boolean
    description: "If true all collaborations can use this service"
    example: true
  automatic_connection_allowed:
    type: boolean
    description: "If true all collaborations can connect to this service"
    example: true
  non_member_users_access_allowed:
    type: boolean
    description: "If true then non collaboration members can access this service"
    example: true
  override_access_allowed_all_connections:
    type: boolean
    description: "If true in combination access_allowed_for_all equals true then connections need to be requested"
    example: true
  token_enabled:
    type: boolean
    description: "If true then tokens can be created for users"
    example: true
  allow_restricted_orgs:
    type: boolean
    description: "If true, this service is allowed to be connected to collaborations of restricted organisations"
    example: true
  token_validity_days:
    type: number
    description: "Tokens validity in days"
    example: 30
  accepted_user_policy:
    type: string
    format: uri
    example: "https://service.cloud.example.com/aup"
  privacy_policy:
    type: string
    format: uri
    example: "https://service.cloud.example.com/privacy"
  logo:
    type: string
    format: uri
    descriotion: "URL for the logo"
    example: "http://sram.surf.nl/api/images/collaborations/b7f621e3-de98-4de4-aca0-1573f4eb8339"
  created_at:
    type: number
    description: "The date of the created at in epoch seconds"
    example: 1644015600
  created_by:
    type: string
    description: "UID of the user who created this"
    example: "urn:admin"
  updated_by:
    type: string
    description: "UID of the user who updated this"
    example: "urn:admin"
