---
type: object
properties:
  id:
    type: number
    readOnly: true
    example: 888
  entity_id:
    type: string
    format: url
    example: "https://service.cloud.example.com"
  name:
    type: string
    example: "Cloud research service"
  abbreviation:
    type: string
    example: "cloud"
  description:
    type:
      - string
      - "null"
    example: "A cloud research service."
  uri:
    type:
      - string
      - "null"
    example: "https://service.cloud.example.com"
  uri_info:
    type:
      - string
      - "null"
    example: "More info"
  accepted_user_policy:
    type:
      - string
      - "null"
    format: uri
    example: "https://service.cloud.example.com/aup"
  privacy_policy:
    type:
      - string
      - "null"
    format: uri
    example: "https://service.cloud.example.com/privacy"
  contact_email:
    type:
      - string
      - "null"
    example: "jdoe@cloud.example.com"
  security_email:
    type:
      - string
      - "null"
    example: "jdoe@cloud.example.com"
  support_email:
    type:
      - string
      - "null"
    example: "jdoe@cloud.example.com"
  logo:
    type:
      - string
      - "null"
    description: "Base64 encoded logo or URL"
    example: "http://sram.surf.nl/api/images/services/b7f621e3"
  uuid4:
    type: string
    format: uuid
    readOnly: true
    example: "12035254-E1F1-4190-9E60-EDAEE8DEE72A"
  access_allowed_for_all:
    type:
      - boolean
      - "null"
    description: "If true all collaborations can use this service"
    example: false
  automatic_connection_allowed:
    type:
      - boolean
      - "null"
    description: "If true all collaborations can connect to this service without approval"
    example: true
  non_member_users_access_allowed:
    type:
      - boolean
      - "null"
    description: "If true non collaboration members can access this service"
    example: false
  override_access_allowed_all_connections:
    type:
      - boolean
      - "null"
    description: "If true in combination with access_allowed_for_all, connections need to be requested"
    example: false
  allow_restricted_orgs:
    type:
      - boolean
      - "null"
    description: "If true this service is allowed to be connected to collaborations of restricted organisations"
    example: false
  token_enabled:
    type:
      - boolean
      - "null"
    description: "If true tokens can be created for users"
    example: false
  token_validity_days:
    type:
      - number
      - "null"
    description: "Token validity in days"
    example: 30
  pam_web_sso_enabled:
    type:
      - boolean
      - "null"
    example: false
  ldap_enabled:
    type:
      - boolean
      - "null"
    example: false
  ldap_identifier:
    type: string
    example: "ldap_id"
  ldap_password:
    type:
      - string
      - "null"
    example: ""
  saml_enabled:
    type:
      - boolean
      - "null"
    example: false
  acs_locations:
    type:
      - string
      - "null"
    description: "Comma-separated ACS locations"
    example: "https://sp.example.com/acs"
  oidc_enabled:
    type:
      - boolean
      - "null"
    example: false
  oidc_client_secret:
    type:
      - string
      - "null"
    example: ""
  is_public_client:
    type:
      - boolean
      - "null"
    example: false
  grants:
    type:
      - string
      - "null"
    description: "Comma-separated OIDC grant types"
    example: "authorization_code, refresh_token"
  redirect_urls:
    type:
      - string
      - "null"
    description: "Comma-separated redirect URLs"
    example: "https://redirect.com/url1,https://redirect.com/url2"
  connection_setting:
    type:
      - string
      - "null"
    example: "on_request"
  scim_enabled:
    type:
      - boolean
      - "null"
    example: false
  scim_url:
    type:
      - string
      - "null"
    example: "https://scim.example.com"
  scim_bearer_token:
    type:
      - string
      - "null"
    example: ""
  scim_client_enabled:
    type:
      - boolean
      - "null"
    example: false
  sweep_scim_enabled:
    type:
      - boolean
      - "null"
    example: false
  sweep_scim_daily_rate:
    type:
      - number
      - "null"
    example: 1
  sweep_scim_last_run:
    type:
      - number
      - "null"
    description: "Last SCIM sweep run timestamp in epoch seconds"
    example: 0
  sweep_remove_orphans:
    type:
      - boolean
      - "null"
    example: false
  export_successful:
    type:
      - boolean
      - "null"
    example: false
  exported_at:
    type:
      - number
      - "null"
    description: "Export timestamp in epoch seconds"
    example: 0
  export_external_identifier:
    type:
      - string
      - "null"
    example: ""
  export_external_version:
    type:
      - number
      - "null"
    example: 1
  crm_organisation_id:
    type:
      - number
      - "null"
    example: 1
  support_email_unauthorized_users:
    type:
      - boolean
      - "null"
    example: false
  access_allowed_for_crm_organisation:
    type:
      - boolean
      - "null"
    example: false
  providing_organisation:
    type:
      - string
      - "null"
    example: "SURF"
  organisation_name:
    type:
      - string
      - "null"
    description: "Name of the organisation that owns this service (computed)"
    example: "University of Harderwijk"
  created_at:
    type: number
    description: "Created timestamp in epoch seconds"
    example: 1644015600
  updated_at:
    type: number
    description: "Updated timestamp in epoch seconds"
    example: 1644015600
  created_by:
    type: string
    description: "UID of the user who created this"
    example: "urn:admin"
  updated_by:
    type: string
    description: "UID of the user who updated this"
    example: "urn:admin"
