import {library} from '@fortawesome/fontawesome-svg-core'
import {
    faAngleDown,
    faAngleUp,
    faArrowDown,
    faArrowLeft,
    faArrowRight,
    faArrowUp,
    faBook,
    faCalendarAlt,
    faCaretDown,
    faCaretUp,
    faCheck,
    faCheckCircle,
    faCircle,
    faCopy,
    faDoorClosed,
    faDoorOpen,
    faEnvelope,
    faExternalLinkAlt,
    faGavel,
    faGlobe,
    faHistory,
    faInfo,
    faInfoCircle,
    faLightbulb,
    faLink,
    faLock,
    faLockOpen,
    faMailBulk,
    faPlus,
    faPlusCircle,
    faPencilAlt,
    faQuestion,
    faQuestionCircle,
    faSearch,
    faTimes,
    faToolbox,
    faTrash,
    faUserFriends,
    faUserLock,
    faUsers,
    faUserSecret,
    faWindowClose,
    faFileUpload,
    faPlaneDeparture
} from '@fortawesome/free-solid-svg-icons'

export function addIcons() {
    library.add(faLightbulb, faCalendarAlt, faArrowLeft, faCopy, faGavel, faLink, faBook, faCheckCircle, faInfoCircle, faInfo,
        faCircle, faCheck, faDoorClosed, faAngleDown, faAngleUp, faHistory, faMailBulk,faPencilAlt,
        faPlus, faPlusCircle, faSearch, faFileUpload, faWindowClose, faArrowRight, faExternalLinkAlt, faArrowUp, faArrowDown,
        faQuestion, faQuestionCircle, faToolbox, faEnvelope, faTrash, faTimes, faCaretUp, faCaretDown, faUserSecret, faUserLock,
        faLock, faLockOpen, faGlobe, faUserFriends, faDoorOpen, faUsers, faPlaneDeparture
    );
}
